files:
  - source: '*.md'
    translation: /locales/%two_letters_code%/%original_path%/%original_file_name%
  - source: '*.yml'
    translation: /locales/%two_letters_code%/%original_path%/%original_file_name%
