id: tx-origin-phishing-attack
name: tx.origin Phishing Attack
summary: Learn why using tx.origin for authentication is dangerous and how attackers exploit it for phishing. Understand the difference between tx.origin and msg.sender.
level: 2
priority: 30
tags:
- Solidity
- Security
steps:
- name: tx.origin Phishing Attack
  path: intro
- name: Vulnerable Contract Example
  path: bank
- name: Attack Contract
  path: attack
- name: Reproducing tx.origin Phishing Attack on Remix
  path: remix
- name: Preventing tx.origin Phishing Attack
  path: prevent
  
