---
id: multisigCourse
name: Multisig Wallet
summary: Learn how to create and interact with a multisig wallet. Developed by the p2p learning platform https://dacade.org.
level: 1
tags:
  - Solidity
  - Tokens
  - Multisig
steps:
  - name: 1. Introducción
    path: 1-multisig-introduction

  - name: 2. Inicializar el contrato
    path: 2-multisig-initialization

  - name: 3. Depósitos
    path: 3-multisig-deposits

  - name: 4. Transacciones
    path: 4-multisig-transactions

  - name: 5. Revocación de confirmaciones
    path: 5-multisig-revoke
